ir_qweb: Avoid failures when using qweb not within a HTTP request.
Some tests were failing with:

    Traceback (most recent call last):
      File "odoo9/addons/report/tests/test_reports.py", line 34, in test_reports
        registry('report').get_html(cr, uid, report_model_ids, r.report_name)

      ...

      File "odoo9/openerp/addons/base/ir/ir_qweb.py", line 480, in render_tag_call_assets
        request = getattr(qwebcontext.get('request'), 'httprequest', None)
      File "/home/manu/.virtualenvs/o9/local/lib/python2.7/site-packages/werkzeug/local.py", line 338, in __getattr__
        return getattr(self._get_current_object(), name)
      File "/home/manu/.virtualenvs/o9/local/lib/python2.7/site-packages/werkzeug/local.py", line 297, in _get_current_object
        return self.__local()
      File "/home/manu/.virtualenvs/o9/local/lib/python2.7/site-packages/werkzeug/local.py", line 132, in _lookup
        raise RuntimeError('object unbound')
    QWebException: object unbound

Because when testing qweb there's no need to create a HTTP request.