jobs: Don't remove thread's dbname unconditionally.
This fixes an issue while validating an invoice with celery.  It enter an
infinite recursion loop in sql_db:

    Traceback (most recent call last):
      File "celery/app/trace.py", line 374, in trace_task
        R = retval = fun(*args, **kwargs)
      File "celery/app/trace.py", line 629, in __protected_call__
        return self.run(*args, **kwargs)
      File "odoo/jobs.py", line 765, in task
        res = method(*args, **kwargs)
      File "xopgi_account_celery/base.py", line 85, in _do_validate
        res = count(until_timeout(_validate()))
        ....
        cr = self._cursor = registry(self.dbname).cursor()
      File "odoo/sql_db.py", line 488, in __getattr__
        cr = self._cursor = registry(self.dbname).cursor()
      File "odoo/sql_db.py", line 488, in __getattr__
        cr = self._cursor = registry(self.dbname).cursor()
      File "odoo/sql_db.py", line 488, in __getattr__
        cr = self._cursor = registry(self.dbname).cursor()
      File "odoo/sql_db.py", line 488, in __getattr__
        cr = self._cursor = registry(self.dbname).cursor()
      File "odoo/sql_db.py", line 488, in __getattr__
        cr = self._cursor = registry(self.dbname).cursor()
      File "...", line -1, in [rest of traceback truncated]
    RuntimeError: maximum recursion depth exceeded while calling a Python object

The actual problem is in the `_send` function: it created a new
OdooEnvironment in to communicate with the bus.  This made reporting progress
to remove the dbname attribute and when the LazyCursor checks for it, it
encounters an AttributeError.

Neither Odoo 8, 9 suffer from this, since _send does not use OdooEnvironment
there.

Here fix both issues:

- Avoid deleting dbname in any code path enter the OdooEnvironment twice

- Don't use it in the `_send`.  This actually removes some overhead.